### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by Seeloewen** [Seeloewen/SealSync#3]
Before releasing the first full version of this software, a few things need to be added.

- [ ] Add a debug log - This allows for more transparency on what the software does and helps with fixing issues
- [ ] Settings Rework - Rework the settings to be saved in a file and add new settings
- [ ] Major redesign - To make the software more appealing, components like buttons will be redesigned and a darkmode will be added
- [ ] Translation support - This will make the software easier to use for people worldwide

There's not ETA on when version 1.0 comes out, but I'm aiming at 2024.
